var Factorio = Factorio || {};
Factorio.recipes = {
	raw_wood : {
		icon : "raw-wood.png",
		name : "原木",
		query : "原木(Raw-wood)",
		quantity : 10.0,
		time : 0.5,
		category : "resource",
		ingredients : [],
		factory : ["hand"],
	},
	coal : {
		icon : "coal.png",
		name : "石炭",
		query : "石炭(Coal)",
		quantity : 0.5715,
		time : 1.0,
		category : "resource",
		ingredients : [],
		factory : ["burner_mining_drill", "electric_mining_drill"],
	},
	iron_ore : {
		icon : "iron-ore.png",
		name : "鉄鉱石",
		query : "鉄鉱石(Iron-ore)",
		quantity : 0.5715,
		time : 1.0,
		category : "resource",
		ingredients : [],
		factory : ["burner_mining_drill", "electric_mining_drill"],
	},
	copper_ore : {
		icon : "copper-ore.png",
		name : "銅鉱石",
		query : "銅鉱石(Copper-ore)",
		quantity : 0.5715,
		time : 1.0,
		category : "resource",
		ingredients : [],
		factory : ["burner_mining_drill", "electric_mining_drill"],
	},
	stone : {
		icon : "stone.png",
		name : "石",
		query : "石(Stone)",
		quantity : 0.5715,
		time : 1.0,
		category : "resource",
		ingredients : [],
		factory : ["burner_mining_drill", "electric_mining_drill"],
	},
	wood : {
		icon : "wood.png",
		name : "木材",
		query : "木材(Wood)",
		quantity : 2.0,
		time : 0.5,
		category : "crafting",
		ingredients : [["raw_wood", 1]],
		factory : ["assembling_machine_1", "assembling_machine_2", "assembling_machine_3"],
	},
	iron_plate : {
		icon : "iron-plate.png",
		name : "鉄板",
		query : "鉄板(Iron-plate)",
		quantity : 1.0,
		time : 3.5,
		category : "smelting",
		ingredients : [["iron_ore", 1]],
		factory : ["stone_furnace", "steel_furnace", "electric_furnace"],
	},
	copper_plate : {
		icon : "copper-plate.png",
		name : "銅板",
		query : "銅板(Copper-plate)",
		quantity : 1.0,
		time : 3.5,
		category : "smelting",
		ingredients : [["copper_ore", 1]],
		factory : ["stone_furnace", "steel_furnace", "electric_furnace"],
	},
	copper_cable : {
		icon : "copper-cable.png",
		name : "銅線",
		query : "銅線(Copper-cable)",
		quantity : 2.0,
		time : 0.5,
		category : "crafting",
		ingredients : [["copper_plate", 1]],
		factory : ["assembling_machine_1", "assembling_machine_2", "assembling_machine_3"],
	},
	electronic_circuit : {
		icon : "electronic-circuit.png",
		name : "電子基板",
		query : "電子基板(Electronic-circuit)",
		quantity : 1.0,
		time : 0.5,
		category : "crafting",
		ingredients : [["iron_plate", 1], ["copper_cable", 3]],
		factory : ["assembling_machine_1", "assembling_machine_2", "assembling_machine_3"],
	},
	burner_mining_drill : {
		icon : "burner-mining-drill.png",
		name : "燃料式掘削機",
		query : "燃料式掘削機(Burner-mining drill)",
		quantity : 1.0,
		time : 2.0,
		category : "crafting",
		ingredients : [["iron_gear_wheel", 3], ["stone_furnace", 1], ["iron_plate", 3]],
		factory : ["assembling_machine_1", "assembling_machine_2", "assembling_machine_3"],
	},
	basic_mining_drill : {
		icon : "basic-mining-drill.png",
		name : "電動掘削機",
		query : "電動掘削機(Electric-mining-drill)",
		quantity : 1.0,
		time : 2.0,
		category : "crafting",
		ingredients : [["electronic_circuit", 3], ["iron_gear_wheel", 5], ["iron_plate", 10]],
		factory : ["assembling_machine_1", "assembling_machine_2", "assembling_machine_3"],
	},
};
